### ISSUE TITLE
Imagens do treino não aparece

### ISSUE THREAD

**Issue by grossiter04** [dan-albuquerque/fds-gymbro#2]
As imagens do banco de dados, da área de treinos não estão renderizando.
![image](https://user-images.githubusercontent.com/116268469/231798068-7c3aba5f-2582-4fa4-aa12-99c5e390437f.png)

**Comment by gabrielpires-1** [comment]
O endereço da imagem de cada treino na classe Treinos no banco de dados estava errado. Alterei e coloquei o endereço correto das imagens, que é: static/img
