### ISSUE TITLE
validation error na aba planejamentos

### ISSUE THREAD

**Issue by grossiter04** [dan-albuquerque/fds-gymbro#22]
quando clico em confirmar do planejamento sem inserir nenhum horario a pagina para de carregar e aparece o erro validation error

**Comment by gabrielpires-1** [comment]
Resolvido. Agora existe uma verificação que insere uma mensagem de erro quando o usuário confirma um horário sem inserir uma hora. Para mais informações, visualizar o commit "Resolvendo issue #22".
