### ISSUE TITLE
Bug na aba de histórico: AttributeError quando não há treinos planejados

### ISSUE THREAD

**Issue by gabrielpires-1** [dan-albuquerque/fds-gymbro#24]
Ao selecionar a aba de histórico sem ter treinos planejados, acontece uma falha com AttributeError:

![image](https://github.com/dan-albuquerque/fds-gymbro/assets/111147078/9d1d69cb-5867-400d-b58d-dc19db6f8224)

Além disso, ao finalizar o **primeiro** treino, a aba de histórico mostra que foram realizados 0 treinos pelo usuário (ao invés de 1)

![image](https://github.com/dan-albuquerque/fds-gymbro/assets/111147078/f1577aa5-5a58-4279-ba30-609cdb8cf80d)

Da mesma forma, ao finalizar 2 treinos, aparece a seguinte mensagem em histórico: "Atualmente você realizou 1 treinos conosco! Continue assim, bro!" ao invés de 2 treinos.

**Comment by CarlosAugustoP** [comment]
ERRO DE SINTAXE. EM VIEWS A CLASSE historico FOI ALTERADA PARA Historico. Verificação se se há treinos. Se não há, 0.
