### ISSUE TITLE
bug na aba sono

### ISSUE THREAD

**Issue by grossiter04** [dan-albuquerque/fds-gymbro#7]
![image](https://user-images.githubusercontent.com/116268469/232339979-73035b28-c7ef-4f02-b321-eca93f057b39.png)
Os inputs do HTML não estão sendo direcionados da forma correta pro banco de dados

**Comment by gabrielpires-1** [comment]
Resolvido. O problema era que o form do sono.html (linha 58) não possuía um atributo action, a linha foi alterada para: action="{% url 'sono_selecionado' %}". Além disso, a view sono_selecionado() não possuía uma url, então não poderia ser acessada. Foi adicionada a linha path('sono_selecionado', sono_selecionado, name="sono_selecionado") em urls.py. Outro problema era que o objeto sono que havia sido criado no banco de dados por algum motivo possuía pk = 5, enquanto que na view é específicado que para alterar o objeto ele deve ter pk = 1. Dessa forma, foi criado um objeto com pk = 1 com os seguintes comandos no shell do django: 

from galeria.models import Sono
sono = Sono(pk=1, dormiu=0, acordou=0)
sono.save()

Agora quando os valores são alterados na aba do sono, também são alterados no banco de dados.

**Comment by gabrielpires-1** [comment]
Resolvido. O problema era que o form do sono.html (linha 58) não possuía um atributo action, a linha foi alterada para: action="{% url 'sono_selecionado' %}". Além disso, a view sono_selecionado() não possuía uma url, então não poderia ser acessada. Foi adicionada a linha path('sono_selecionado', sono_selecionado, name="sono_selecionado") em urls.py. Outro problema era que o objeto sono que havia sido criado no banco de dados por algum motivo possuía pk = 5, enquanto que na view é específicado que para alterar o objeto ele deve ter pk = 1. Dessa forma, foi criado um objeto com pk = 1 com os seguintes comandos no shell do django: 

from galeria.models import Sono
sono = Sono(pk=1, dormiu=0, acordou=0)
sono.save()

Agora quando os valores são alterados na aba do sono, também são alterados no banco de dados.
